### PR TITLE
[ENG-3629] Document which dplyr-based queries fail on DuckDB

### LINKED ISSUE #54: Document which dplyr-based queries fail on DuckDB
The queries all should work (since they use dplyr pipelines), though some of them error:

One can do so with:
```
library(arrowbench)
run_benchmark(
  tpc_h,
  engine = "duckdb",
  scale_factor = 1,
)
```

```
Running engine=duckdb query_id=1 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h

Running engine=duckdb query_id=2 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
  [=>---------------------------------------------------]   5% in  9s eta:  3m
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error: Garbage collection 15 = 11+1+3 (level 0) ... 
42.7 Mbytes of cons cells used (62%)
10.1 Mbytes of vectors used (16%)
Garbage collection 16 = 12+1+3 (level 0) ... 
44.6 Mbytes of cons cells used (65%)
10.7 Mbytes of vectors used (17%)
Garbage collection 17 = 13+1+3 (level 0) ... 
46.2 Mbytes of cons cells used (67%)
11.2 Mbytes of vectors used (17%)
Garbage collection 18 = 14+1+3 (level 0) ... 
46.8 Mbytes of cons cells used (68%)
11.4 Mbytes of vectors used (18%)
Garbage collection 19 = 15+1+3 (level 0) ... 
47.0 Mbytes of cons cells used (69%)
11.4 Mbytes of vectors used (18%)
Garbage collection 20 = 16+1+3 (level 0) ... 
47.1 Mbytes of cons cells used (69%)
11.5 Mbytes of vectors used (18%)
Garbage collection 21 = 17+1+3 (level 0) ... 
47.2 Mbytes of cons cells used (69%)
11.5 Mbytes of vectors used (18%)
Garbage collection 22 = 18+1+3 (level 0) ... 
47.2 Mbytes of cons cells used (69%)
11.5 Mbytes of vectors used (18%)
Error in .local(conn, statement, ...) : 
  duckdb_prepare
Execution halted
Running engine=duckdb query_id=3 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
Running engine=duckdb query_id=4 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
Running engine=duckdb query_id=5 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
Running engine=duckdb query_id=6 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
Running engine=duckdb query_id=7 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
  [=============>---------------------------------------]  27% in 50s eta:  2m
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error in duckdb_execute(res) : duckdb_execute_R: Failed to run query
Error: Catalog Error: Table with name "nation" already exists!
Calls: run_bm ... dbSendQuery -> .local -> duckdb_result -> duckdb_execute
Execution halted
Running engine=duckdb query_id=8 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
  [================>------------------------------------]  32% in  1m eta:  2m
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error in duckdb_execute(res) : duckdb_execute_R: Failed to run query
Error: Catalog Error: Table with name "nation" already exists!
Calls: run_bm ... dbSendQuery -> .local -> duckdb_result -> duckdb_execute
Execution halted
Running engine=duckdb query_id=9 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
  [==================>----------------------------------]  36% in  1m eta:  2m
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error: Garbage collection 15 = 11+1+3 (level 0) ... 
42.7 Mbytes of cons cells used (62%)
10.1 Mbytes of vectors used (16%)
Garbage collection 16 = 12+1+3 (level 0) ... 
44.6 Mbytes of cons cells used (65%)
10.7 Mbytes of vectors used (17%)
Garbage collection 17 = 13+1+3 (level 0) ... 
46.2 Mbytes of cons cells used (67%)
11.2 Mbytes of vectors used (17%)
Garbage collection 18 = 14+1+3 (level 0) ... 
46.9 Mbytes of cons cells used (68%)
11.4 Mbytes of vectors used (18%)
Garbage collection 19 = 15+1+3 (level 0) ... 
47.1 Mbytes of cons cells used (69%)
11.5 Mbytes of vectors used (18%)
Garbage collection 20 = 16+1+3 (level 0) ... 
47.1 Mbytes of cons cells used (69%)
11.5 Mbytes of vectors used (18%)
Error in .local(conn, statement, ...) : 
  duckdb_prepare_R: Failed to prepare query SELECT "nation", "o_year", SUM("amount") AS "sum_profit"
FROM (SELECT "n_name" AS "nation", EXTRACT(year FROM "o_orderdate") AS "o_year", "l_extendedprice" * (1.0 - "l_discount") - "ps_supplycost" * "l_quan
Execution halted
Running engine=duckdb query_id=10 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
Running engine=duckdb query_id=11 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
Running engine=duckdb query_id=12 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
Running engine=duckdb query_id=13 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
  [============================>------------------------]  55% in  2m eta:  1m
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error: Garbage collection 15 = 11+1+3 (level 0) ... 
42.7 Mbytes of cons cells used (62%)
10.1 Mbytes of vectors used (16%)
Garbage collection 16 = 12+1+3 (level 0) ... 
44.6 Mbytes of cons cells used (65%)
10.7 Mbytes of vectors used (17%)
Garbage collection 17 = 13+1+3 (level 0) ... 
46.2 Mbytes of cons cells used (67%)
11.2 Mbytes of vectors used (17%)
Error in .local(conn, statement, ...) : 
  duckdb_prepare_R: Failed to prepare query SELECT "c_count", COUNT(*) AS "custdist"
FROM (SELECT "c_custkey", SUM(NOT((("o_orderkey") IS NULL))) AS "c_count"
FROM (SELECT "c_custkey", "c_name", "c_address", "c_nationkey", "c_phone", "c_acctbal", "c_mktsegment", "c_comment", "o_orderkey", "o_orderstatus", "o_totalprice", "o_orderdate", "o_orderpriority", "o_clerk", "o_shippriority", "o_comment"
FROM "customer" AS "LHS"
LEFT JOIN (SELECT *
FROM "orders"
WHERE (NOT(grepl('special.*?requests', "o_comment")))) "RHS"
ON ("LHS"."c_custkey" = "RHS"."o_custkey")
) "q01"
GROUP BY "c_custkey") "q02"
GROU
Execution halted
Running engine=duckdb query_id=14 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
  [==============================>----------------------]  59% in  2m eta:  1m
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error: Garbage collection 15 = 11+1+3 (level 0) ... 
42.7 Mbytes of cons cells used (62%)
10.1 Mbytes of vectors used (16%)
Garbage collection 16 = 12+1+3 (level 0) ... 
44.6 Mbytes of cons cells used (65%)
10.7 Mbytes of vectors used (17%)
Garbage collection 17 = 13+1+3 (level 0) ... 
46.0 Mbytes of cons cells used (67%)
11.1 Mbytes of vectors used (17%)
Error in .local(conn, statement, ...) : 
  duckdb_prepare_R: Failed to prepare query SELECT 100.0 * SUM(CASE WHEN (grepl('^PROMO', "p_type")) THEN ("l_extendedprice" * (1.0 - "l_discount")) WHEN NOT(grepl('^PROMO', "p_type")) THEN (0.0) END) / SUM("l_extendedprice" * (1.0 - "l_discount")) AS "promo_revenue"
FROM (SELECT "l_orderkey", "l_partkey", "l_suppkey", "l_linenumber", "l_quantity", "l_extendedprice", "l_discount", "l_tax", "l_returnflag", "l_linestatus", "l_shipdate", "l_commitdate", "l_receiptdate", "l_shipinstruct", "l_shipmode", "l_comment", "p_name", "p_mfgr", "p_brand", "p_type", "p_size", "p_container", "p_retailprice", "
Execution halted
Running engine=duckdb query_id=15 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
Running engine=duckdb query_id=16 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
  [===================================>-----------------]  68% in  2m eta:  1m
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error: Garbage collection 15 = 11+1+3 (level 0) ... 
42.7 Mbytes of cons cells used (62%)
10.1 Mbytes of vectors used (16%)
Garbage collection 16 = 12+1+3 (level 0) ... 
44.6 Mbytes of cons cells used (65%)
10.7 Mbytes of vectors used (17%)
Garbage collection 17 = 13+1+3 (level 0) ... 
46.7 Mbytes of cons cells used (68%)
11.3 Mbytes of vectors used (18%)
Garbage collection 18 = 14+1+3 (level 0) ... 
47.0 Mbytes of cons cells used (69%)
11.4 Mbytes of vectors used (18%)
Error in .local(conn, statement, ...) : 
  duckdb_prepare_R: Failed to prepare query SELECT "p_brand", "p_type", "p_size", "supplier_cnt"
FROM (SELECT "p_brand", "p_type", "p_size", COUNT(DISTINCT "ps_suppkey") AS "supplier_cnt"
FROM (SELECT "p_partkey", "p_name", "p_mfgr", "p_brand", "p_type", "p_size", "p_container", "p_retailprice", "p_comment", "ps_suppkey"
FROM (SELECT *
FROM "part"
WHERE (("p_brand" != 'Brand#45') AND (NOT(grepl('^MEDIUM POLISHED', "p_type"))) AND ("p_size" IN (49.0, 14.0, 23.0, 45.0, 19.0, 3.0, 3
Execution halted
Running engine=duckdb query_id=17 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
Running engine=duckdb query_id=18 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
Running engine=duckdb query_id=19 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
Running engine=duckdb query_id=20 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
  [=============================================>-------]  86% in  2m eta: 22s
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error: Garbage collection 15 = 11+1+3 (level 0) ... 
42.7 Mbytes of cons cells used (62%)
10.1 Mbytes of vectors used (16%)
Garbage collection 16 = 12+1+3 (level 0) ... 
44.6 Mbytes of cons cells used (65%)
10.7 Mbytes of vectors used (17%)
Garbage collection 17 = 13+1+3 (level 0) ... 
46.7 Mbytes of cons cells used (68%)
11.4 Mbytes of vectors used (18%)
Garbage collection 18 = 14+1+3 (level 0) ... 
47.0 Mbytes of cons cells used (69%)
11.4 Mbytes of vectors used (18%)
Garbage collection 19 = 15+1+3 (level 0) ... 
47.2 Mbytes of cons cells used (69%)
11.5 Mbytes of vectors used (18%)
Garbage collection 20 = 16+1+3 (level 0) ... 
47.2 Mbytes of cons cells used (69%)
11.5 Mbytes of vectors used (18%)
Error in .local(conn, statement, ...) : 
  duckdb_prepare_R: Failed to prepare query SELECT "s_name", "s_address"
FROM (SELECT * FROM (SELECT "s_suppkey", "s_name", "s_address"
FROM (SELECT "s_suppkey", "s_name", "s_address", "s_nationkey", "s_phone", "s_acctbal", "s_comment", "n_name", "n_
Execution halted
Running engine=duckdb query_id=21 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
  [===============================================>-----]  91% in  2m eta: 14s
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error in duckdb_execute(res) : duckdb_execute_R: Failed to run query
Error: Catalog Error: Table with name "lineitem" already exists!
Calls: run_bm ... dbSendQuery -> .local -> duckdb_result -> duckdb_execute
Execution halted
Running engine=duckdb query_id=22 format=native scale_factor=1 memory_map=FALSE cpu_count=10 lib_path=latest name=tpc_h
  [==================================================>--]  95% in  3m eta:  7s
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error in duckdb_execute(res) : duckdb_execute_R: Failed to run query
Error: Catalog Error: Table with name "customer" already exists!
Calls: run_bm ... dbSendQuery -> .local -> duckdb_result -> duckdb_execute
Execution halted
  [=====================================================] 100% in  3m eta:  0s
10 benchmarks errored:
   engine query_id format scale_factor memory_map cpu_count lib_path
2  duckdb        2 native            1      FALSE        10   latest
7  duckdb        7 native            1      FALSE        10   latest
8  duckdb        8 native            1      FALSE        10   latest
9  duckdb        9 native            1      FALSE        10   latest
13 duckdb       13 native            1      FALSE        10   latest
14 duckdb       14 native            1      FALSE        10   latest
16 duckdb       16 native            1      FALSE        10   latest
20 duckdb       20 native            1      FALSE        10   latest
21 duckdb       21 native            1      FALSE        10   latest
22 duckdb       22 native            1      FALSE        10   latest
Total run time: 2.528341 mins
```

### PR DESCRIPTION
**Pull request by boshek**
When merged this will close #54

### CODE REVIEW

File: R/tpch-queries.R [hunk 1]
```diff
@@ -695,7 +695,7 @@ tpc_h_queries[[21]] <- function(input_func, collect_func = dplyr::collect, con =
     inner_join(input_func("orders"), by = c("l_orderkey" = "o_orderkey")) %>%
     filter(o_orderstatus == "F") %>%
     group_by(l_orderkey, l_suppkey) %>%
-    summarise(failed_delivery_commit = any(l_receiptdate > l_commitdate)) %>%
+    summarise(failed_delivery_commit = sum(ifelse(l_receiptdate > l_commitdate, 1L, 0L))) %>%
```
Comment (jonkeane) [inline R/tpch-queries.R:698]:
```suggestion
    summarise(failed_delivery_commit = sum(l_receiptdate > l_commitdate) > 0) %>%
```

Would this work too?

Comment (boshek) [reply R/tpch-queries.R:698]: I don't think it will because I don't think SQL won't sum logicals like R. Could be missing something but that's what this tells me:
``` r
library(dplyr, warn.conflicts = FALSE)
library(duckdb)
#> Loading required package: DBI

con <- DBI::dbConnect(duckdb::duckdb(), ":memory:")
duckdb_register(con, "iris", iris)

iris %>%
  mutate(log = Species == "setosa") %>%
  summarise(log_sum = sum(log))
#>   log_sum
#> 1      50

tbl(con, "iris") %>%
  mutate(log = Species == "setosa") %>%
  summarise(log_sum = sum(log))
#> Warning: Missing values are always removed in SQL.
#> Use `SUM(x, na.rm = TRUE)` to silence this warning
#> This warning is displayed only once per session.
#> Error: duckdb_prepare_R: Failed to prepare query SELECT SUM("log") AS "log_sum"
#> FROM (
#>   SELECT
#>     "Sepal.Length",
#>     "Sepal.Width",
#>     "Petal.Length",
#>     "Petal.Width",
#>     "Species",
#>     "Species" = 'setosa' AS "log"
#>   FROM "iris"
#> ) "q01"
#> LIMIT 11
#> Error: Binder Error: No function matches the given name and argument types 'sum(BOOLEAN)'. You might need to add explicit type casts.
#>  Candidate functions:
#>  sum(DECIMAL) -> DECIMAL
#>  sum(SMALLINT) -> HUGEINT
#>  sum(INTEGER) -> HUGEINT
#>  sum(BIGINT) -> HUGEINT
#>  sum(HUGEINT) -> HUGEINT
#>  sum(DOUBLE) -> DOUBLE
#> 
#> LINE 1: SELECT SUM("log") AS "log_sum"
#>                ^
```

Comment (boshek) [reply R/tpch-queries.R:698]: Yeah that look nicer for sure. The issue is that it returns a logical so we will need to add `as.integer` below as well:

```r
  summarise(failed_delivery_commit = sum(as.integer(l_receiptdate > l_commitdate)) > 0) %>%
  group_by(l_orderkey) %>%
  summarise(
    n_supplier = n(),
    num_failed = sum(as.integer(failed_delivery_commit))
  ) %>%
 ```

Comment (jonkeane) [reply R/tpch-queries.R:707]: Heh, that's funny — but ok so long as we're still getting the right results at the various scale factors!

File: R/tpch-queries.R [hunk 2]
```diff
@@ -29,14 +29,23 @@ tpc_h_queries[[1]] <- function(input_func, collect_func = dplyr::collect, con =
...
+  if (engine == "duckdb") {
+    p <- p %>%
+      filter(p_type %like% "%BRASS") %>%
+      select(p_partkey, p_mfgr)
+  } else {
+    p <- p %>%
+      filter(grepl(".*BRASS$", p_type)) %>%
+      select(p_partkey, p_mfgr)
+
+  }
```
Comment (boshek) [inline R/tpch-queries.R:48]: @jonkeane jsut looking for a little feedback about this approach before giving the same treatment to the other failing queries.

File: R/tpch-queries.R [hunk 3]
```diff
@@ -29,14 +29,23 @@ tpc_h_queries[[1]] <- function(input_func, collect_func = dplyr::collect, con =
     collect_func()
 }
 
-tpc_h_queries[[2]] <- function(input_func, collect_func = dplyr::collect, con = NULL) {
+tpc_h_queries[[2]] <- function(input_func, collect_func = dplyr::collect, con = NULL, engine) {
```
Comment (jonkeane) [inline R/tpch-queries.R:32]:
```suggestion
tpc_h_queries[[2]] <- function(input_func, collect_func = dplyr::collect, con = NULL, grep_func = grepl) {
```

File: R/tpch-queries.R (hunk 2 above)
Comment (jonkeane) [inline R/tpch-queries.R:48]:
```suggestion
      filter(p_size == 15, grep_func(".*BRASS$", p_type)) %>%
      select(p_partkey, p_mfgr)
```

**Review by jonkeane — COMMENTED** [review]
I was thinking something like these changes, and then you put around here:

https://github.com/ursacomputing/arrowbench/blob/6ff8af0dd62d36a57fc7b9571753af360d7c9cb9/R/bm-tpc-h.R#L49

```
    if (engine == "duckdb") {
      grep_func <- `%like%`
    } else {
      grep_func <- grepl
    }
```

Though I'm sure there are a few other things you'll need to do to get that all connected.

**Comment by boshek** [comment]
So I'd added a custom `grepl` function only to find out that `grepl` is already part of the dev version of the duckdb package: https://github.com/duckdb/duckdb/blob/662041e2b43283bfcfeed984af7c3eaa85fb4996/tools/rpkg/R/backend-dbplyr__duckdb_connection.R#L70-L84

Curious your take but my sense is to drop what is honestly an hacky solution that I came up with and simply wait for the next release on duckdb at which point the existing syntax should _just work_.

**Comment by jonkeane** [comment]
> So I'd added a custom grepl function only to find out that grepl is already part of the dev version of the duckdb package

Aaaaah, yeah we should definitely just leave as is. It turns out, this is not even actually in a dev version — it's already been released, however it's not yet on CRAN. So once DuckDB 0.3.3 gets to cran these will automagically start working. Maybe add a comment (or we can leave #54 open for now) with a note that we should re-check when 0.3.3 is here?

**Comment by boshek** [comment]
I'll just keep an eye on CRAN and act accordingly when duckdb 0.3.3 is released.

File: tests/testthat/test-bm-tpc-h.R [hunk 4]
```diff
@@ -140,3 +140,29 @@ ORDER BY
...
+    engine = "duckdb",
+    query_id = c(2, 9, 13, 14, 16, 20),
+    scale_factor = 1
+  )
+  no_fails <- any(vapply(run, function(x) is.null(x$error), logical(1)))
+  expect_true(no_fails)
+})
+
+
+test_that("query 21 use of logicals passed",{
```
Comment (jonkeane) [inline tests/testthat/test-bm-tpc-h.R:158]:
```suggestion
test_that("query 21 use of logicals passed", {
```

Very minor style nit

File: tests/testthat/test-bm-tpc-h.R [hunk 5]
```diff
@@ -140,3 +140,29 @@ ORDER BY
...
 })
+
+
+test_that("grepl queries work with dbplyr style sql", {
+  skip_if_not_installed("duckdb", minimum_version = "0.3.3")
+  run <- run_benchmark(
+    tpc_h,
+    engine = "duckdb",
+    query_id = c(2, 9, 13, 14, 16, 20),
+    scale_factor = 1
```
Comment (jonkeane) [inline tests/testthat/test-bm-tpc-h.R:151]: Could we use scale factor 0.001 here? That should be much quicker in CI.

File: tests/testthat/test-bm-tpc-h.R [hunk 6]
```diff
@@ -140,3 +140,29 @@ ORDER BY
...
+  expect_true(no_fails)
+})
+
+
+test_that("query 21 use of logicals passed",{
+  run <- run_benchmark(
+    tpc_h,
+    engine = "duckdb",
+    query_id = 21,
+    scale_factor = 1
```
Comment (jonkeane) [inline tests/testthat/test-bm-tpc-h.R:163]: Could we use scale factor 0.001 here? That should be much quicker in CI.

**Review by jonkeane — APPROVED** [review]
This looks good, a few minor changes. Once you address those feel free to merge
